class CenelecDatas {
  static Map<String, String> dp = {
    'A': 'استاندارد ملی تایید شده',
    'H': 'استاندارد همگون',
    'N': 'کابل ملی',
  };
  static Map<String, String> nv = {
    '01': '100-300 v',
    '03': '300/300 V',
    '05': '300/500 V',
    '07': '450/750 V',
  };
  static Map<String, String> se = {
    'A': 'هادی آلومینیوم هم محور',
    'A6': 'هادی آلومینیوم هم محور با هادی شکل داده شده',
    'C': 'هادی مسی هم محور',
    'C6': 'هادی مسی هم محور با هادی شکل داده شده',
    'C9': 'هادی مسی هم محور جدا سازی شده',
    'A7': 'اسکرین الومینیومی',
    'A8': 'اسکرین الومینیومی با هادی های جدا از هم',
    'C4': 'اسکرین بافت مسی',
    'C5': 'اسکرین بافت مسی برای هادی های جدا از هم',
    'C7': 'اسکرین نوار مسی',
    'C8': 'اسکرین نوار مسی برای هادی های جدا از هم',
    'D': 'اسکرین برای یکی یا چند نوار فولادی ',
    'Z2': 'ارمور شده با سیم های گرد',
    'Z3': 'ارمور شده  با سیم های تخت',
    'Z4': 'ارمور شده با نوار فولادی',
    'Z5': 'ارمور شده با بافت فولادی',
    'Z6': 'حفاظت شده با بافت فولادی',
    'Z7': 'ارمور شده با فولاد مقطعی',
    'Y2': 'ارمور  شده با سیم های الومینیومی',
    'Y3': 'ارمور شده با سیم های تخت الومینیومی',
    'Y5': 'ارمور شده با مواد خاص',
    'Y6': 'ارمورشده با سیم فولادی و یا سیم و نوار مسی',
  };
  static Map<String, String> cm = {
    'A': 'الومینیوم',
    'Z': 'مواد خاص و یا شکل خاص',
    ' ': 'مس طراحی شده',
  };
  static Map<String, String> sdf = {
    'D2': 'بافت یا سیم های فولادی روی هادی کابل',
    'D3': 'جز بافته تابیده شده به همراه کابل',
    'D4': 'کابل ها و سیم های  خود نگهدار ',
    'D5': 'جز مرکزی هادی',
    'W/O': 'کابل گرد طراحی شده ',
    'H': 'کابل تخت با یا بدون  جدا کننده',
    'H2': 'نوع تخت از کابل که جدا نشده اند',
    'H3': 'کابل ساختمانی تخت مشبک',
    'H4': 'کابل تخت چند رشته با یک هادی ساده',
    'H5': 'دو یا چند هادی استرند شده بدون روکش',
    'H6': 'کابل تخت با تعداد سه یا بیشتر هادی',
    'H7': 'کابل با عایق دو لایه',
    'H8': 'هادی کویل شده ',
  };
  static Map<String, String> ct = {
    'D': 'هادی های نازک تابیده شده برای کابل جوش',
    'E': 'هادی های بسیار نازک تابیده شده برای کابل جوش',
    'F': 'هادی نازک تابیده شده برای کابل های قابل انعطاف (کلاس  5)',
    'H': 'هادی های بسیار نازک تابیده شده برای کابل های قابل انعطاف(کلاس 6)',
    'K': 'هادی نازک تابیده شده برای نصب ثابت (کلاس 5)',
    'M': 'هادی میلیکن ( جهت کابل های ولتاژ بالا)',
    'R': 'هادی متشکل از استرند های بهم تابیده شده ( کلاس 2)',
    'S': 'هادی های چند سیمه شکل داده شده به صورت سکتور',
    'U': 'هادی گرد از سیم تک رشته ( کلاس 1)',
    'W': 'هادی شکل داده شده سکتور از مفتول تک رشته',
    'Y': 'هادی tinsel( هادی یا نوار باریک پیچیده شده دور الیاف)',
    'Z': 'هادی متشکل از مواد ویا ساختار خاص',
  };
  static Map<String, String> pc = {
    'G': 'به همراه سیم زرد خط سبز ( ارت )',
    'X': 'بدون سیم ارت',
  };
  static Map<String, String> iAndsm = {
    'B': 'Ethylene-propylene rubber (EPR) +90°C ',
    'B2': 'Ethylene-propylene rubber (EPR), hardened',
    'B3': 'Butyl rubber',
    'E': 'Polyethylene  PE',
    'E2': 'Polyethylene, high density',
    'E4': 'Poly-tetrafluorethylene',
    'E5': 'Eethylene propylene rubber',
    'E6': 'Ethylene tetrafluorethylene',
    'E7': 'Polypropylene',
    'G': "Ethylene-vinylacetate (EVA RUBBER ) 110' C",
    'J': 'Glass fibre braiding',
    'J2': 'Glass fibre wrapping',
    'M': 'Mineral insulation',
    'N': 'Chloroprene rubber (CR)',
    'N2': 'Chloroprene-rubber (CR), welding cable',
    'N4': 'Chlorinated polyethylene  CPE',
    'N5': 'Nitril-rubber',
    'N6': 'Fluorinated rubber',
    'N7': 'PVC nitril rubber compound',
    'N8': 'Polychloroprene rubber, water resistant',
    'P': 'Impregnated paper insulation',
    'Q': 'Polyurethane (PUR)',
    'Q2': 'Polyethyleneterephthalate',
    'Q3': 'Polystyrole',
    'Q4': 'Polyamide',
    'Q5': 'Polyamide',
    'Q6': 'Polyvinylidene fluoride',
    'R': "(NR, SR) natural or synthetic rubber 60'C",
    'S': '(SIR) silicone rubber',
    'T': 'Textile braiding',
    'T2': 'Textile braiding with flame retardant',
    'T3': 'Textile conductor wrapping or tape',
    'T4': 'Textile conductor wrapping or tape, flame retardant',
    'T5': 'Corrosion protection',
    'T6': 'Textile braiding over individual conductor or cable',
    'V': "PVC  70°C",
    'V2': 'PVC soft, resistant to increased temperature, +90°C',
    'V3': 'PVC soft, for low temperatures',
    'V4': 'PVC soft, cross-linked    XPVC',
    'V5': 'PVC soft, oil resistant',
    'X': 'Cross-linked polyethylene  XLPE',
    'Z': 'K',
    'Z1': 'Thermoplastic compound, LSZH',
  };
  static Map<String, String> number = {
    '1': '1',
    '2': '2',
    '3': '3',
    '4': '4',
    '5': '5',
    '6': '6',
    '7': '7',
    '8': '8',
    '9': '9',
    '10': '10',
    '11': '11',
    '12': '12',
    '13': '13',
    '14': '14',
    '15': '15',
    '16': '16',
    '17': '17',
    '18': '18',
    '19': '19',
    '20': '20',
    '21': '21',
    '22': '22',
    '23': '23',
    '24': '24',
    '25': '25',
    '26': '26',
    '27': '27',
    '28': '28',
    '29': '29',
    '30': '30',
  };
  static Map<String, String> size = {
    '0.25': '0.25',
    '0.5': '0.5',
    '0.75': '0.75',
    '1': '1',
    '1.5': '1.5',
    '2.5': '2.5',
    '4': '4',
    '6': '6',
    '10': '10',
    '16': '16',
    '25': '25',
    '35': '35',
    '50': '50',
    '70': '70',
    '95': '95',
    '120': '120',
    '150': '150',
    '185': '185',
    '200': '200',
    '240': '240',
    '300': '300',
  };
}
